#!/bin/bash

SOURCE_VAULT="$1"
DEST_VAULT="$2"

for secret_id in $(az keyvault secret list --vault-name $SOURCE_VAULT --query "[].id" -o tsv); do
    secret_name=$(basename $secret_id)
    secret_value=$(az keyvault secret show --id $secret_id --query "value" -o tsv)
    az keyvault secret set --vault-name $DEST_VAULT --name $secret_name --value "$secret_value"
done
