- hosts: localhost
  vars:
    uuid: 'myuuuid'
  become: yes
  gather_facts: no
  tasks:
    - include_vars: ./lsattr.vars.yml

    - name: jinja
      set_fact:
        luns: >
          [{
          {% for entry in results -%}
             {% for inner in entry.stdout_lines %}
               {% if inner.split(' ')[0] == uuid %}
                 "{{ entry.item.name }}": "{{ inner.split(' ')[1] }}",
               {% endif %}
             {% endfor %}
          {% endfor %}
          }]

    - debug:
        var: luns

    - debug:
        var: results

    - name: test
      debug:
        msg: "{{ item }}"
      with_dict: "{{ luns }}"
