---

# Assumes thats the correct secrets are allready set for the VC.
# --------------------------------------------------------------

- name: Grow VMware disk backing an LVM VG, then grow LVM VG in guest
  hosts: all
  gather_facts: false
  become: true

  pre_tasks:
    - name: Check inputs, limit to 1T for a volume group.
      ansible.builtin.assert:
        that:
          - desired_disk_size_gb is defined
          - desired_disk_size_gb | int > 32
          - desired_disk_size_gb | int < 1024
        fail_msg: |
          desired_disk_size_gb needs to be set no more than 1024G

    - name: Check inputs, limit to 1T for a volume group.
      ansible.builtin.assert:
        that:
          - vg_name is defined
          - vg_name | length
        fail_msg: |
          desired_disk_size_gb needs to be set no more than 1024G

  tasks:

    - name: Check VG exists
      block:
        - name: Gather LVM facts
          ansible.builtin.setup:
            gather_subset:
              - hardware

        - name: Does the VG exist
          ansible.builtin.assert:
            that:
              - vg_name in ansible_lvm.vgs
            fail_msg: |
              VG does not exist

    - name: Find PV device(s) for VG
      ansible.builtin.command: >
        pvs --noheadings --separator ' ' -o pv_name --select vg_name={{ vg_name }}
      register: pvs_out
      changed_when: false

    - name: Pick first PV (adjust if your VG spans multiple PVs)
      ansible.builtin.set_fact:
        pv_device: "{{ ( pvs_out.stdout_lines | map('trim') | reject('equalto','') | list )[0] }}"

    - name: Get base disk (PKNAME) for PV (handles /dev/sdb2 -> sdb)
      ansible.builtin.command: "lsblk -no PKNAME {{ pv_device }}"
      register: pkname_out
      changed_when: false

    - name: Set base disk path
      ansible.builtin.set_fact:
        base_disk: "/dev/{{ pkname_out.stdout_lines | first }}"

    - name: Get current base disk size (bytes)
      ansible.builtin.command: "lsblk -b -dn -o SIZE {{ base_disk }}"
      register: disksize_out
      changed_when: false

    - name: Compute current size in GB (floor)
      ansible.builtin.set_fact:
        current_disk_size_gb: "{{ (disksize_out.stdout | int // (1024**3)) }}"

    - name: Find /dev/disk/by-path symlink for this base disk (SCSI mapping)
      ansible.builtin.shell: |
        set -euo pipefail
        real="$(readlink -f {{ base_disk }})"
        ls -l /dev/disk/by-path | awk -v r="../../${real##*/}" '$NF==r {print $9}' | head -n1
      args:
        executable: /bin/bash
      register: bypath_out
      changed_when: false

    - name: Parse SCSI address from by-path (expects ...-scsi-H:C:T:L)
      ansible.builtin.set_fact:
        scsi_host: "{{ (bypath_out.stdout | regex_search('scsi-(\\d+):(\\d+):(\\d+):(\\d+)', '\\1')) | int }}"
        scsi_target: "{{ (bypath_out.stdout | regex_search('scsi-(\\d+):(\\d+):(\\d+):(\\d+)', '\\3')) | int }}"

    - name: Show what we think the VMware address is
      ansible.builtin.debug:
        msg:
          - "VG={{ vg_name }} PV={{ pv_device }} base_disk={{ base_disk }}"
          - "by-path={{ bypath_out.stdout }}"
          - "VMware mapping guess: scsi_controller(bus)={{ scsi_host }}, unit_number={{ scsi_target }}"
          - "Current disk size: {{ current_disk_size_gb }} GB, desired: {{ desired_disk_size_gb }} GB"

    - name: Set datacenter
      ansible.builtin.set_fact:
        datacenter: >-
          {{ os_provision.cluster | default('NGSP') if os_provision is defined else 'NGSP' }}

    - name: Expand VMware disk if it is smaller than desired
      delegate_to: localhost
      become: false
      when: current_disk_size_gb | int < desired_disk_size_gb | int
      community.vmware.vmware_guest_disk:
        datacenter: "{{ datacenter }}"
        # cluster: "PPCF" #"{{ vmware_folder }}"
        # @@SGM we need to check this
        name: "{{ inventory_hostname }}"
        disk:
          - state: present
            size_gb: "{{ desired_disk_size_gb | int }}"
            scsi_controller: "{{ scsi_host | int }}"
            unit_number: "{{ scsi_target | int }}"
      register: disk_change

    - name: Rescan the disk in Linux (kernel notices new size)
      when: current_disk_size_gb | int < desired_disk_size_gb | int
      ansible.builtin.shell: |
        set -euo pipefail
        echo 1 > /sys/class/block/{{ base_disk | regex_replace('^/dev/','') }}/device/rescan
      args:
        executable: /bin/bash

    - name: If PV is a partition, grow the partition to fill the disk (requires growpart)
      when:
        - current_disk_size_gb | int < desired_disk_size_gb | int
        - pv_device is match('^/dev/[a-z]+d[a-z]+[0-9]+$') or pv_device is match('^/dev/nvme[0-9]+n[0-9]+p[0-9]+$')
      ansible.builtin.shell: |
        set -euo pipefail
        parted -s -m -a optimal {{ base_disk }} -- resizepart 2 100%
      args:
        executable: /bin/bash

    - name: pvresize (make LVM see the extra space)
      when: current_disk_size_gb | int < desired_disk_size_gb | int
      ansible.builtin.command: "pvresize {{ pv_device }}"
      register: pvresize_out

    - name: notify kernel
      when: current_disk_size_gb | int < desired_disk_size_gb | int
      ansible.builtin.command: "partprobe {{ base_disk }}"
      register: pvresize_out

    - name: Show output of PVs
      ansible.builtin.command: pvs
      register: pvs

    - name: Showing PVs
      ansible.builtin.debug:
        msg: "{{ pvs.stdout.splitlines() }}"
...
