---
# Generic "get all pages" helper:
# - expects: url_in, results_var, validate_certs_in, token_in
# - sets:   <results_var> as a flat list

- name: Init pagination state
  ansible.builtin.set_fact:
    _next_url: "{{ url_in }}"
    _results: []

- name: Paginate until next is null
  ansible.builtin.include_tasks: paginate_step.yml
  until: _next_url is none
  retries: 1000
  delay: 0

- name: Publish results
  ansible.builtin.set_fact:
    "{{ results_var }}": "{{ _results }}"
